import {
  SiteEditorSettings,
  Product,
  ProductCategory,
  SitePage,
} from "./theme-types";

export const sampleCategories: ProductCategory[] = [
  {
    id: "cat-1",
    slug: "women",
    name: "Women",
    description: "Tailored dresses, structured jackets, and handwoven jamdani silk",
    image: "/assets/cat-wo.jpg",
    banner: "/assets/cat-wo.jpg",
    icon: "",
    itemCount: 24,
    featured: true,
  },
  {
    id: "cat-2",
    slug: "men",
    name: "Men",
    description: "Relaxed linen overshirts, tussar silk panjabis, and tailoring",
    image: "/assets/cat-man.jpg",
    banner: "/assets/cat-man.jpg",
    icon: "",
    itemCount: 18,
    featured: true,
  },
  {
    id: "cat-3",
    slug: "bags",
    name: "Bags",
    description: "Vegetable-tanned leather totes, shoulder bags, and artisan backpacks",
    image: "/assets/cat-bag.jpg",
    banner: "/assets/cat-bag.jpg",
    icon: "",
    itemCount: 20,
    featured: true,
  },
  {
    id: "cat-4",
    slug: "shoes",
    name: "Shoes",
    description: "Polished Italian calfskin loafers, clean sneakers, and pointed flats",
    image: "/assets/cat-sh.jpg",
    banner: "/assets/cat-sh.jpg",
    icon: "",
    itemCount: 15,
    featured: true,
  },
  {
    id: "cat-5",
    slug: "accessories",
    name: "Accessories",
    description: "Stainless steel timepieces, classic eyewear, and gold-toned jewelry",
    image: "/assets/cat-ac.jpg",
    banner: "/assets/cat-ac.jpg",
    icon: "",
    itemCount: 25,
    featured: false,
  },
];

export const sampleProducts: Product[] = [
  {
    id: "prod-1",
    slug: "structured-wool-jacket",
    name: "Structured Jacket",
    tagline: "Sand-colored structured jacket tailored for a minimalist silhouette",
    description: "Sand-colored structured jacket tailored for a minimalist silhouette. Cut for a quiet elegance.",
    longDescription: "Engineered from a premium virgin wool blend with structured shoulders and a clean concealed closure. Hand-finished in Italy.",
    price: 8500,
    originalPrice: 10500,
    discountPercent: 19,
    images: [
      "/assets/women/1.jpg",
      "/assets/women/2.jpg",
      "/assets/women/3.jpg",
    ],
    categoryId: "cat-1",
    categoryName: "Women",
    freeDelivery: true,
    deliveryCharges: [],
    rating: 4.9,
    reviewCount: 48,
    inStock: true,
    stockCount: 8,
    featured: true,
    details: {
      material: "Premium wool-silk blend",
      origin: "Made in Italy",
      care: "Dry clean only",
      dimensions: "Regular fit, tailored cut",
    },
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "prod-2",
    slug: "relaxed-linen-overshirt",
    name: "Linen Overshirt",
    tagline: "Relaxed light-beige linen overshirt with visible texture",
    description: "Relaxed light-beige linen overshirt with visible texture. Uncomplicated design for everyday wear.",
    longDescription: "Crafted from 100% organic European flax. Breathable, durable, and naturally textured with horn buttons.",
    price: 3850,
    originalPrice: 4500,
    discountPercent: 14,
    images: [
      "/assets/men/1.jpg",
      "/assets/men/2.jpg",
      "/assets/men/3.jpg",
    ],
    categoryId: "cat-2",
    categoryName: "Men",
    freeDelivery: true,
    deliveryCharges: [],
    rating: 4.8,
    reviewCount: 36,
    inStock: true,
    stockCount: 15,
    featured: true,
    details: {
      material: "100% Organic European Linen",
      origin: "Made in Portugal",
      care: "Gentle machine wash cold",
      dimensions: "Relaxed fit",
    },
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "prod-3",
    slug: "structured-leather-shoulder-bag",
    name: "Structured Shoulder Bag",
    tagline: "Italian calfskin leather with subtle brass hardware",
    description: "Structured women's shoulder bag in polished Italian calfskin. Minimalist rectangular form.",
    longDescription: "Constructed with clean magnetic flap closure, soft suede interior lining, and dual slip compartments.",
    price: 9500,
    originalPrice: 11500,
    discountPercent: 17,
    images: [
      "/assets/bags/1.jpg",
      "/assets/bags/2.jpg",
      "/assets/bags/3.jpg",
    ],
    categoryId: "cat-3",
    categoryName: "Bags",
    freeDelivery: true,
    deliveryCharges: [],
    rating: 4.9,
    reviewCount: 29,
    inStock: true,
    stockCount: 12,
    featured: true,
    details: {
      material: "Full-grain Italian calfskin",
      origin: "Crafted in Florence",
      care: "Wipe with soft leather conditioner",
      dimensions: "26cm x 18cm x 7cm",
    },
    sizes: ["One Size"],
  },
  {
    id: "prod-4",
    slug: "white-low-top-sneakers",
    name: "Low-Top Sneakers",
    tagline: "Clean white low-top fashion sneakers with premium leather",
    description: "Clean white low-top sneakers in soft nappa leather with durable vulcanized rubber soles.",
    longDescription: "Crafted for understated luxury and all-day comfort. Padded collar, removable insole, and waxed cotton laces.",
    price: 4800,
    originalPrice: 5600,
    discountPercent: 14,
    images: [
      "/assets/shoe/1.jpg",
      "/assets/shoe/2.jpg",
      "/assets/shoe/3.jpg",
    ],
    categoryId: "cat-4",
    categoryName: "Shoes",
    freeDelivery: true,
    deliveryCharges: [],
    rating: 5.0,
    reviewCount: 84,
    inStock: true,
    stockCount: 20,
    featured: true,
    details: {
      material: "Italian nappa leather & rubber sole",
      origin: "Handcrafted in Portugal",
      care: "Clean with damp cloth",
      dimensions: "True to size",
    },
    sizes: ["40", "41", "42", "43", "44"],
  },
  {
    id: "prod-5",
    slug: "minimal-steel-watch",
    name: "Steel Watch",
    tagline: "Minimal stainless-steel wristwatch with clean white dial",
    description: "Minimal stainless-steel automatic timepiece with sapphire crystal glass and brushed metal bracelet.",
    longDescription: "Precision automatic Japanese movement encased in 316L marine-grade stainless steel. Water resistant to 5ATM.",
    price: 12000,
    originalPrice: 14500,
    discountPercent: 17,
    images: [
      "/assets/access/1.jpg",
      "/assets/access/2.jpg",
      "/assets/access/3.jpg",
    ],
    categoryId: "cat-5",
    categoryName: "Accessories",
    freeDelivery: true,
    deliveryCharges: [],
    rating: 4.9,
    reviewCount: 42,
    inStock: true,
    stockCount: 6,
    featured: true,
    details: {
      material: "316L Stainless Steel & Sapphire Glass",
      origin: "Engineered in Tokyo",
      care: "Rinse with fresh water after submersion",
      dimensions: "38mm case diameter",
    },
    sizes: ["One Size"],
  },
  {
    id: "prod-6",
    slug: "minimal-black-dress",
    name: "Minimal Black Dress",
    tagline: "Clean minimal black midi dress with subtle structure",
    description: "Clean minimal black midi dress with subtle structure and fluid satin drape.",
    longDescription: "Woven from silk-blend satin with hidden rear zipper and side split for effortless movement.",
    price: 7200,
    originalPrice: 8500,
    discountPercent: 15,
    images: [
      "/assets/women/4.jpg",
      "/assets/women/5.jpg",
    ],
    categoryId: "cat-1",
    categoryName: "Women",
    freeDelivery: true,
    deliveryCharges: [],
    rating: 4.8,
    reviewCount: 31,
    inStock: true,
    stockCount: 9,
    featured: true,
    details: {
      material: "Heavyweight silk-satin blend",
      origin: "Made in Italy",
      care: "Dry clean recommended",
      dimensions: "Midi length, regular fit",
    },
    sizes: ["XS", "S", "M", "L"],
  },
];

export const sampleSitePages: SitePage[] = [
  { id: "page-1", type: "home", title: "Home", path: "/", enabled: true },
  { id: "page-2", type: "products", title: "Shop", path: "/shop", enabled: true },
  { id: "page-3", type: "categories", title: "Categories", path: "/categories", enabled: true },
  { id: "page-4", type: "cart", title: "Cart", path: "/cart", enabled: true },
  { id: "page-5", type: "checkout", title: "Checkout", path: "/checkout", enabled: true },
  { id: "page-6", type: "about", title: "About", path: "/about", enabled: true },
  { id: "page-7", type: "contact", title: "Contact", path: "/contact", enabled: true },
  { id: "page-8", type: "faq", title: "FAQ", path: "/faq", enabled: true },
  { id: "page-9", type: "privacy", title: "Privacy Policy", path: "/privacy", enabled: true },
  { id: "page-10", type: "terms", title: "Terms", path: "/terms", enabled: true },
  { id: "page-11", type: "productDetail", title: "Product", path: "/shop/:slug", enabled: true },
  { id: "page-12", type: "notFound", title: "Page Not Found", path: "/404", enabled: true },
];

export const defaultSettings: SiteEditorSettings = {
  siteName: "Maison",
  logoType: "text",
  logoImage: "",
  tagline: "Quiet, considered garments made to last",
  primaryColor: "#1c1917",
  accentColor: "#78716c",
  surfaceColor: "#faf9f6",
  displayFont: "fraunces",
  bodyFont: "inter",
  buttonStyle: "Square",
  navLinks: [
    { id: "nav-1", label: "Shop", path: "/shop" },
    { id: "nav-2", label: "Women", path: "/shop?category=women" },
    { id: "nav-3", label: "Men", path: "/shop?category=men" },
    { id: "nav-4", label: "About", path: "/about" },
  ],
  headerButtons: [],
  pages: sampleSitePages,
  sections: [
    { id: "sec-1", type: "hero" },
    { id: "sec-2", type: "banner" },
    { id: "sec-3", type: "categories" },
    { id: "sec-4", type: "featureProducts" },
    { id: "sec-5", type: "productShowcase" },
    { id: "sec-6", type: "testimonials" },
    { id: "sec-7", type: "features" },
    { id: "sec-8", type: "footer" },
  ],
  announcementItems: ["New Season", "Free Shipping Over ৳2,500", "Crafted to Last"],
  announcementDivider: "✦",
  heroImages: ["/assets/hero-1.jpg", "/assets/hero-2.jpg", "/assets/hero-3.jpg"],
  heroImagesSquare: [],
  categoriesTitle: "The collections.",
  selectedCategoryIds: ["cat-1", "cat-2", "cat-3", "cat-4", "cat-5"],
  featureProductsTitle: "New arrivals.",
  selectedProductIds: ["prod-1", "prod-2", "prod-3", "prod-4", "prod-5", "prod-6"],
  showcaseProductId: "prod-1",
  whyTitle: "Why customers trust Maison",
  whyImage: "",
  why1Title: "Guaranteed authentic craft",
  why1: "Worldwide delivery on all orders. Delivered in signature packaging.",
  why2Title: "Fast, secure delivery",
  why2: "Our garments are made to last with complimentary repairs.",
  why3Title: "Real satisfaction, easy returns",
  why3: "Every fiber is ethically sourced from family-run mills.",
  categoryShowcaseTitle: "Shop by collection",
  categoryShowcaseCategoryIds: ["cat-1", "cat-2", "cat-3"],
  featuresTitle: "Our Commitments",
  feature1Title: "Complimentary Delivery",
  feature1: "Worldwide delivery and returns on all orders over ৳2,500. Delivered in signature sustainable packaging.",
  feature1IconKind: "icon",
  feature1Icon: "truck",
  feature1Image: "",
  feature2Title: "Lifetime Heritage Care",
  feature2: "Our garments are made to last. We offer care guides and repairs to keep your pieces in perfect condition.",
  feature2IconKind: "icon",
  feature2Icon: "refresh-cw",
  feature2Image: "",
  feature3Title: "Traceable Origins",
  feature3: "Every fiber is ethically sourced. We partner exclusively with family-run master craft clusters.",
  feature3IconKind: "icon",
  feature3Icon: "leaf",
  feature3Image: "",
  testimonialsTitle: "What our clients say",
  testimonials: [
    {
      id: "test-1",
      name: "Camille Laurent",
      quote: "The texture and drape of the virgin wool jacket are exceptional. Clean, quiet luxury at its very best.",
      image: "/assets/women/1.jpg",
      role: "Paris, France",
      rating: 5,
    },
    {
      id: "test-2",
      name: "Marcus Vance",
      quote: "The linen overshirt is my favorite staple. The construction, weight, and cut are genuinely heirloom quality.",
      image: "/assets/men/1.jpg",
      role: "London, UK",
      rating: 5,
    },
    {
      id: "test-3",
      name: "Elena Rostova",
      quote: "The structured leather bag feels bespoke. Delivered swiftly in immaculate packaging.",
      image: "/assets/bags/1.jpg",
      role: "Milan, Italy",
      rating: 5,
    },
    {
      id: "test-4",
      name: "Arthur Pendelton",
      quote: "The cashmere knitwear is incredibly warm yet lightweight. Exceptionally tailored.",
      image: "/assets/men/2.jpg",
      role: "New York, USA",
      rating: 5,
    },
    {
      id: "test-5",
      name: "Sonia Gauthier",
      quote: "Minimalist aesthetics combined with supreme quality. Highly recommend their bespoke tailoring.",
      image: "/assets/women/2.jpg",
      role: "Geneva, Switzerland",
      rating: 5,
    }
  ],
  ctaTitle: "Join the Maison Journal",
  ctaBody: "Subscribe for private previews, seasonal lookbooks, and quiet stories.",
  ctaButton: "Shop Now",
  footerDescription:
    "Quiet, considered handcrafted garments and artisanal goods designed for a slower pace. Made to last across generations.",
  footerShopLabel: "Shop",
  footerShopLinks: [
    { id: "fs1", label: "Women", path: "/shop?category=women" },
    { id: "fs2", label: "Men", path: "/shop?category=men" },
    { id: "fs3", label: "Bags", path: "/shop?category=bags" },
    { id: "fs4", label: "Accessories", path: "/shop?category=accessories" },
  ],
  footerCompanyLabel: "Company",
  footerCompanyLinks: [
    { id: "fc1", label: "About", path: "/about" },
    { id: "fc2", label: "Collections", path: "/categories" },
    { id: "fc3", label: "FAQ", path: "/faq" },
    { id: "fc4", label: "Contact", path: "/contact" },
  ],
};
